version: "3.7"
services:
  app:
    build:
      args:
        user: rndev_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rndev
    container_name: rndev-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rndev

  db:
    image: mariadb:10.10
    container_name: rndev-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - rndev

  nginx:
    image: nginx:1.23-alpine
    container_name: rndev-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - rndev

networks:
  rndev:
    driver: bridge